stages:
  - test
  - deploy

test:
  image: gcr.io/cloud-builders/kubectl:latest
  stage: test
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - sed -i "s/__JOBNAME__/site-builder-api-test-$CI_COMMIT_SHORT_SHA/" k8s_test.yaml
    - kubectl create -f k8s_test.yaml
    - kubectl describe jobs -n default | grep "Pods Statuses"
    - kubectl wait --for=condition=complete --timeout=1m -n default job/site-builder-api-test-$CI_COMMIT_SHORT_SHA
    - pods=$(kubectl get pods -n default --selector=job-name=site-builder-api-test-$CI_COMMIT_SHORT_SHA --output=jsonpath='{.items[*].metadata.name}')
    - kubectl logs -n default $pods
    - kubectl delete -f k8s_test.yaml


deploy to production:
  only:
    refs:
      - main
    kubernetes: active
  image: gcr.io/cloud-builders/kubectl:latest
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - sed -i "s/__VERSION__/gitlab-$CI_COMMIT_SHORT_SHA/" k8s.yaml
    - kubectl apply -f k8s.yaml
    - kubectl rollout status -w deployment/site-builder-api -n default

deploy to develop:
  only:
    refs:
      - develop
    kubernetes: active
  image: gcr.io/cloud-builders/kubectl:latest
  stage: deploy
  environment:
    name: develop
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL_DEV" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN_DEV"
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - sed -i "s/__VERSION__/gitlab-$CI_COMMIT_SHORT_SHA/" k8s.yaml
    - kubectl apply -f k8s.yaml
    - kubectl rollout status -w deployment/site-builder-api -n default
